# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The wilks statistics of Pareto and Stretched-Exponential 
#' @description The wilks statistics of Pareto and Stretched-Exponential 
#' @param x the vector of samples
#' @param u the threshold of domain
#' @return the result of the hypothesis \code{n}
#' @examples
#' \dontrun{
#' wilkstat <- wilks(c(2,3,4,5),1)
#' wilkstat
#' }
#' @export
wilks <- function(x, u) {
    .Call('_SA23204187_wilks', PACKAGE = 'SA23204187', x, u)
}

